<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace theme_nit\local;

/**
 * Hook callbacks for theme_nit.
 *
 * @package    theme_nit
 * @copyright  2026 NIT
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class hook_callbacks {

    /**
     * Force a chrome-free ("embedded") page layout when a page is being viewed
     * inside the mobile app's in-app WebView.
     *
     * Why this exists
     * ---------------
     * The Flutter app renders most content natively, but some activities have no
     * native screen (forums, and generic mod/url, mod/page, mod/book, mod/lesson,
     * mod/scorm, etc.) so it opens the real Moodle page inside a WebView. In that
     * WebView the student must ONLY see the activity material — no site header,
     * footer, breadcrumbs, nav drawer, user/settings menu, activity prev/next,
     * "back to course" or login/logout links — nothing that lets them roam the
     * wider site or leave the activity.
     *
     * Moodle already ships exactly such a stripped layout: `embedded` (used for
     * iframes/filepickers). Switching the whole app WebView session to it gives us
     * chrome-free rendering server-side, so the app needs no CSS/JS injection.
     *
     * This runs on `before_http_headers`, which core dispatches at the very top of
     * core_renderer::header() BEFORE the page state moves to PRINTING_HEADER and
     * BEFORE the layout file is resolved — so set_pagelayout() here still takes
     * effect. Desktop/browser users are never affected: the detection below only
     * matches the app.
     *
     * Detection (any one is enough):
     *   1. `core_useragent::is_moodle_app()` — the WebView sends a User-Agent
     *      containing "MoodleMobile" (recommended; same signal the app already
     *      uses on its web-service calls). This is the cleanest single trigger.
     *   2. `?nitembed=1` on the URL — a fallback the app can append to the
     *      autologin `urltogo` target if it cannot change the WebView UA.
     *   3. A session flag we set on the first match — because in-activity links
     *      generated by core (e.g. a forum discussion, a reply form) carry
     *      neither signal, but they ARE loaded in the same isolated WebView
     *      session, so the flag keeps them chrome-free too.
     *
     * The session flag lives only in the WebView's own cookie jar / session, which
     * is separate from any desktop browser session, so it can never leak the
     * embedded layout to web users.
     *
     * @param \core\hook\output\before_http_headers $hook
     */
    public static function before_http_headers(\core\hook\output\before_http_headers $hook): void {
        global $PAGE, $SESSION;

        if (empty($PAGE)) {
            return;
        }

        // Never touch layouts that are already chrome-free or must not be altered.
        $skiplayouts = ['embedded', 'maintenance', 'redirect', 'print'];
        if (in_array($PAGE->pagelayout, $skiplayouts, true)) {
            return;
        }

        // Route Moodle's default course index / category browse to the T1
        // catalogue (local_nit_category), so every "all courses" / "all
        // categories" link lands on the designed page. Course MANAGEMENT
        // (/course/management.php, a different pagetype) is untouched, so staff
        // still have the real management UI. Runs on before_http_headers — early
        // enough for a clean redirect before any output.
        $pt = $PAGE->pagetype ?? '';
        if (($pt === 'course-index' || $pt === 'course-index-category')
                && file_exists($GLOBALS['CFG']->dirroot . '/local/nit_category/index.php')) {
            $catid = optional_param('categoryid', 0, PARAM_INT);
            redirect(new \moodle_url('/local/nit_category/index.php', $catid ? ['id' => $catid] : []));
        }

        // Route a user's OWN profile to the T1 "Profile & settings" page. Viewing
        // someone else's profile (an admin/teacher) is left on the core page.
        if ($pt === 'user-profile'
                && file_exists($GLOBALS['CFG']->dirroot . '/local/academy/profile.php')
                && isloggedin() && !isguestuser()) {
            global $USER;
            $viewid = optional_param('id', (int) $USER->id, PARAM_INT);
            if ($viewid === (int) $USER->id) {
                redirect(new \moodle_url('/local/academy/profile.php'));
            }
        }

        // Is this the app's WebView? Sticky for the rest of the (WebView-only) session.
        $isapp = !empty($SESSION->theme_nit_appembed)
            || \core_useragent::is_moodle_app()
            || (bool) optional_param('nitembed', 0, PARAM_BOOL);

        if (!$isapp) {
            return;
        }

        // Remember, so subsequent in-activity page loads stay chrome-free even
        // when they carry neither the app User-Agent nor the ?nitembed param.
        $SESSION->theme_nit_appembed = 1;

        $PAGE->set_pagelayout('embedded');
    }

    /**
     * Inject the login/signup page background inline in <head>, computed fresh from
     * the current stored file each request (theme_nit_loginbg_url()). Replaces the
     * deprecated `before_standard_html_head` plugin callback, which — with developer
     * debugging on — printed a migration notice mid-<head> and corrupted the page.
     *
     * @param \core\hook\output\before_standard_head_html_generation $hook
     */
    public static function before_standard_head_html_generation(
        \core\hook\output\before_standard_head_html_generation $hook
    ): void {
        global $PAGE, $CFG;
        $pagetype = $PAGE->pagetype ?? '';
        // login-index, login-signup, login-forgot_password, … all start with "login".
        if (strpos($pagetype, 'login') !== 0) {
            return;
        }
        require_once($CFG->dirroot . '/theme/nit/lib.php');
        try {
            $url = theme_nit_loginbg_url(\theme_config::load('nit'));
        } catch (\Throwable $e) {
            return;
        }
        if ($url === '') {
            return;
        }
        $safe = str_replace(["\\", "'", "\r", "\n", '"'], ['\\5c ', '\\27 ', '', '', ''], $url);
        // Paint the LEFT panel only (the branded side of the two-column login) —
        // never the whole page, or the image bleeds behind the form.
        $css = '.login-layout-left{'
            . "background-image:linear-gradient(rgba(0,0,0,.45),rgba(0,0,0,.6)),url('" . $safe . "')!important;"
            . 'background-size:cover!important;background-position:center center!important;'
            . 'background-repeat:no-repeat!important;}';
        $hook->add_html('<style id="nit-login-bg-live">' . $css . '</style>');
    }

    /**
     * The T1 "Editing homepage" toolbar — the design's "Edit page" screen.
     *
     * Shown only on the site front page (pagetype site-index) while the owner has
     * edit mode ON. It gives the branded "you are editing" indicator from the
     * design plus two REAL controls: "View page" (opens the live homepage in a new
     * tab, editing preserved) and "Done editing" (Moodle's edit=off toggle). There
     * is deliberately no "Publish"/"Saved 2 min ago": Moodle's front-page block
     * editing is live — changes persist immediately — so a draft/publish workflow
     * would be design-only. The bar sits above the (kept) navbar, so it never
     * removes an existing control. Structure is hardcoded dark (an editing chrome);
     * only the primary action carries the academy accent.
     *
     * @param \core\hook\output\before_standard_top_of_body_html_generation $hook
     */
    public static function before_standard_top_of_body_html_generation(
        \core\hook\output\before_standard_top_of_body_html_generation $hook
    ): void {
        global $PAGE;

        // Course pages: a floating "Rate this course" button for enrolled learners
        // who can review (local_nit_reviews). Links to the plugin's rate page.
        $pt = $PAGE->pagetype ?? '';
        if (strpos($pt, 'course-view') === 0
                && class_exists('\local_nit_reviews\api')
                && !empty($PAGE->course->id) && (int) $PAGE->course->id > 1
                && \local_nit_reviews\api::can_rate((int) $PAGE->course->id)) {
            $label = (strpos(current_language(), 'ar') === 0) ? 'قيّم هذه الدورة' : 'Rate this course';
            $rateurl = (new \moodle_url('/local/nit_reviews/rate.php', ['courseid' => $PAGE->course->id]))->out(false);
            $hook->add_html('<a href="' . $rateurl . '" id="nit-rate-fab" style="'
                . 'position:fixed; inset-inline-end:20px; bottom:20px; z-index:1030;'
                . 'display:inline-flex; align-items:center; gap:8px; text-decoration:none;'
                . 'background:var(--nit-brand-primary,#0E7C66); color:var(--nit-brand-on-primary,#fff);'
                . "font-family:'Manrope','IBM Plex Sans Arabic',system-ui,sans-serif; font-weight:600; font-size:14px;"
                . 'padding:12px 18px; border-radius:999px; box-shadow:0 10px 26px rgba(20,24,28,.22);">'
                . '<span style="font-size:16px;">&#9733;</span> ' . s($label) . '</a>');
        }

        if ($pt !== 'site-index') {
            return;
        }
        if (!method_exists($PAGE, 'user_is_editing') || !$PAGE->user_is_editing()) {
            return;
        }

        $isar = (strpos(current_language(), 'ar') === 0);
        $t = fn(string $en, string $ar) => $isar ? $ar : $en;

        $doneurl = (new \moodle_url('/', ['edit' => 'off', 'sesskey' => sesskey()]))->out(false);
        $viewurl = (new \moodle_url('/'))->out(false);

        $label = s($t('Editing homepage', 'تحرير الصفحة الرئيسية'));
        $hint  = s($t('Drag sections to reorder — changes save automatically.',
            'اسحب الأقسام لإعادة الترتيب — تُحفظ التغييرات تلقائيًا.'));
        $view  = s($t('View page', 'معاينة'));
        $done  = s($t('Done editing', 'إنهاء التحرير'));

        $html = '<div id="nit-edit-toolbar" dir="' . ($isar ? 'rtl' : 'ltr') . '" style="'
            . 'background:#16191D;color:#fff;font-family:\'Manrope\',\'IBM Plex Sans Arabic\',system-ui,sans-serif;">'
            . '<div style="max-width:1240px;margin:0 auto;padding:12px 24px;display:flex;align-items:center;gap:16px;flex-wrap:wrap;">'
            . '<span style="display:flex;align-items:center;gap:9px;font-size:13px;font-weight:600;">'
            . '<span style="width:7px;height:7px;border-radius:50%;background:#E0A100;display:block;"></span>' . $label . '</span>'
            . '<span style="font-size:12px;color:#9CA3AA;">' . $hint . '</span>'
            . '<span style="margin-inline-start:auto;display:flex;align-items:center;gap:10px;">'
            . '<a href="' . $viewurl . '" target="_blank" rel="noopener" style="'
            . 'font-size:13px;font-weight:600;background:rgba(255,255,255,0.1);border:1px solid rgba(255,255,255,0.18);'
            . 'color:#fff;padding:9px 16px;border-radius:8px;text-decoration:none;">' . $view . '</a>'
            . '<a href="' . $doneurl . '" style="'
            . 'font-size:13px;font-weight:600;background:var(--nit-brand-primary,#0E7C66);border:0;'
            . 'color:var(--nit-brand-on-primary,#fff);padding:10px 18px;border-radius:8px;text-decoration:none;">' . $done . '</a>'
            . '</span></div></div>';

        $hook->add_html($html);
    }
}
