<?php
/**
 * Token-authorised question-image endpoint (quiz slice).
 *
 * Serves question-bank files (question text / answer options / general feedback) to the
 * app, authorising by web-service token + course enrolment instead of an active quiz
 * attempt context (which the standard webservice/pluginfile.php route requires).
 *
 * URLs are generated by quiz_manager::local_file_url().
 * Adapted to the Moodle 4.x/5.x question bank: a question is linked to courses/contexts
 * through question_versions → question_references → quiz_slots (not quiz_slots.questionid),
 * and its context comes from question_bank_entries → question_categories.
 */

define('NO_MOODLE_COOKIES', true);
require(__DIR__ . '/../../config.php');
require_once($CFG->libdir . '/filelib.php');

$token      = optional_param('token', '', PARAM_RAW);
$questionid = required_param('questionid', PARAM_INT);
$area       = required_param('area', PARAM_ALPHANUMEXT);
$itemid     = required_param('itemid', PARAM_INT);
$filename   = required_param('file', PARAM_FILE);

if (!in_array($area, ['questiontext', 'answer', 'generalfeedback'], true)) {
    send_file_not_found();
}

// ── Authenticate token → user (full validation: expiry, IP, service, account) ──
$user = \local_academy\token_auth::validate($token);
if (!$user) {
    header('HTTP/1.1 401 Unauthorized');
    die('Invalid token');
}
\core\session\manager::set_user($user);
$userid = (int) $user->id;

$isadmin = has_capability('local/academy:manageplatform', context_system::instance(), $userid);

// ── Authorise: admins bypass; students must be enrolled in a course whose quiz uses it ──
if (!$isadmin) {
    $courses = $DB->get_fieldset_sql("
        SELECT DISTINCT q.course
          FROM {question_versions} qv
          JOIN {question_references} qr ON qr.questionbankentryid = qv.questionbankentryid
               AND qr.component = 'mod_quiz' AND qr.questionarea = 'slot'
          JOIN {quiz_slots} slot ON slot.id = qr.itemid
          JOIN {quiz} q ON q.id = slot.quizid
         WHERE qv.questionid = :questionid", ['questionid' => $questionid]);

    $allowed = false;
    foreach ($courses as $cid) {
        if (is_enrolled(context_course::instance($cid), $userid, '', true)) {
            $allowed = true;
            break;
        }
    }
    if (!$allowed) {
        header('HTTP/1.1 403 Forbidden');
        die('Not allowed');
    }
}

// ── Resolve the question's file context (question category context) ──
$contextid = $DB->get_field_sql("
    SELECT qc.contextid
      FROM {question_versions} qv
      JOIN {question_bank_entries} qbe ON qbe.id = qv.questionbankentryid
      JOIN {question_categories} qc ON qc.id = qbe.questioncategoryid
     WHERE qv.questionid = :questionid", ['questionid' => $questionid], IGNORE_MULTIPLE);

if (!$contextid) {
    send_file_not_found();
}

$fs   = get_file_storage();
$file = $fs->get_file($contextid, 'question', $area, $itemid, '/', $filename);
if (!$file || $file->is_directory()) {
    send_file_not_found();
}

send_stored_file($file, 86400, 0, false);
